// Better Brooklyn Nine-Nine Quotes Database
const betterB99Quotes = {
    holt: [
        { quote: "BONE?!", emoji: "🦴" },
        { quote: "VINDICATION!", emoji: "✨" },
        { quote: "HOT DAMN!", emoji: "🔥" },
        { quote: "BOOOOOOONE?!", emoji: "🦴" },
        { quote: "WUNCH TIME IS OVER!", emoji: "⏰" },
        { quote: "I AM YOUR SUPERIOR OFFICER!", emoji: "👔" },
        { quote: "YAS QUEEN!", emoji: "👑" },
        { quote: "BINGPOT!", emoji: "🎯" },
        { quote: "I'M A HUMAN. I'M A HUMAN MALE.", emoji: "👨" },
        { quote: "EVERY TIME SOMEONE STEPS UP AND SAYS WHO THEY ARE, THE WORLD BECOMES A BETTER, MORE INTERESTING PLACE.", emoji: "🌈" },
        { quote: "I'M TOO OLD TO BE A 43!", emoji: "👴" },
        { quote: "I'M A GENIUS. I'M A GENIUS. I'M A GENIUS.", emoji: "🧠" }
    ],
    jake: [
        { quote: "COOL COOL COOL COOL COOL!", emoji: "😎" },
        { quote: "NO DOUBT NO DOUBT!", emoji: "👍" },
        { quote: "TITLE OF YOUR SEX TAPE!", emoji: "📹" },
        { quote: "I'M TOO YOUNG TO DIE!", emoji: "💀" },
        { quote: "OH DAMN! OH DAMN! OH DAMN!", emoji: "😱" },
        { quote: "I'M THE HUMAN FORM OF THE 100 EMOJI!", emoji: "💯" },
        { quote: "I'M A GENIUS!", emoji: "🧠" },
        { quote: "I'M A DETECTIVE!", emoji: "🔍" },
        { quote: "I'M A COP!", emoji: "👮" },
        { quote: "I'M A HERO!", emoji: "🦸" },
        { quote: "I'M A LEGEND!", emoji: "🌟" },
        { quote: "I'M A STAR!", emoji: "⭐" },
        { quote: "I'M A BADASS!", emoji: "💪" },
        { quote: "I'M A WINNER!", emoji: "🏆" },
        { quote: "I'M A CHAMPION!", emoji: "🥇" },
        { quote: "I'M THE BEST!", emoji: "👑" },
        { quote: "I'M A LEADER!", emoji: "🎖️" },
        { quote: "I'M A WARRIOR!", emoji: "⚔️" },
        { quote: "I'M A PROTECTOR!", emoji: "🛡️" },
        { quote: "I'M A GUARDIAN!", emoji: "🦸‍♂️" },
        { quote: "I'M A SAVIOR!", emoji: "🦸‍♂️" },
        { quote: "I'M A LEGENDARY DETECTIVE!", emoji: "🔍" },
        { quote: "I'M THE GREATEST COP EVER!", emoji: "👮‍♂️" }
    ],
    amy: [
        { quote: "I'M A COMPLETE FREAK!", emoji: "📚" },
        { quote: "I LOVE RULES!", emoji: "📋" },
        { quote: "I'M A TOTAL FREAK!", emoji: "📖" },
        { quote: "I LOVE ORGANIZATION!", emoji: "📁" },
        { quote: "I LOVE BINDERS!", emoji: "📒" },
        { quote: "I LOVE PLANNING!", emoji: "📅" },
        { quote: "I LOVE SCHEDULES!", emoji: "⏰" },
        { quote: "I LOVE LISTS!", emoji: "📝" },
        { quote: "I LOVE ORGANIZING!", emoji: "🗂️" },
        { quote: "I LOVE EFFICIENCY!", emoji: "⚡" },
        { quote: "I'M A FREAK!", emoji: "📚" },
        { quote: "I LOVE BEING A FREAK!", emoji: "📖" },
        { quote: "I'M A TOTAL FREAK!", emoji: "📋" },
        { quote: "I LOVE BEING ORGANIZED!", emoji: "📁" },
        { quote: "I LOVE BEING EFFICIENT!", emoji: "⚡" },
        { quote: "I LOVE BEING PRECISE!", emoji: "🎯" },
        { quote: "I LOVE BEING ACCURATE!", emoji: "🎯" },
        { quote: "I LOVE BEING THOROUGH!", emoji: "🔍" },
        { quote: "I LOVE BEING DETAILED!", emoji: "📋" },
        { quote: "I LOVE BEING SYSTEMATIC!", emoji: "⚙️" },
        { quote: "I LOVE BEING METHODICAL!", emoji: "🔬" },
        { quote: "I LOVE BEING STRUCTURED!", emoji: "🏗️" },
        { quote: "I LOVE BEING ORDERLY!", emoji: "📦" },
        { quote: "I LOVE BEING DISCIPLINED!", emoji: "🎯" }
    ],
    rosa: [
        { quote: "I'M A SAVAGE!", emoji: "😠" },
        { quote: "I'M A BADASS!", emoji: "💪" },
        { quote: "I'M A WARRIOR!", emoji: "⚔️" },
        { quote: "I'M A FIGHTER!", emoji: "🥊" },
        { quote: "I'M A KILLER!", emoji: "🗡️" },
        { quote: "I'M A BEAST!", emoji: "🦁" },
        { quote: "I'M A MONSTER!", emoji: "👹" },
        { quote: "I'M A DEMON!", emoji: "😈" },
        { quote: "I'M A SHARK!", emoji: "🦈" },
        { quote: "I'M A TIGER!", emoji: "🐯" },
        { quote: "I'M A WOLF!", emoji: "🐺" },
        { quote: "I'M A DRAGON!", emoji: "🐉" },
        { quote: "I'M A PHOENIX!", emoji: "🔥" },
        { quote: "I'M A VAMPIRE!", emoji: "🧛‍♀️" },
        { quote: "I'M A WITCH!", emoji: "🧙‍♀️" },
        { quote: "I'M A SORCERESS!", emoji: "🔮" },
        { quote: "I'M A NECROMANCER!", emoji: "💀" },
        { quote: "I'M A DARK LORD!", emoji: "👑" },
        { quote: "I'M A SHADOW!", emoji: "👤" },
        { quote: "I'M A GHOST!", emoji: "👻" },
        { quote: "I'M A SPIRIT!", emoji: "👻" },
        { quote: "I'M A LEGEND!", emoji: "🌟" }
    ],
    terry: [
        { quote: "TERRY LOVES LOVE!", emoji: "💕" },
        { quote: "TERRY LOVES YOGURT!", emoji: "🥛" },
        { quote: "TERRY LOVES HIS KIDS!", emoji: "👶" },
        { quote: "TERRY LOVES WORKING OUT!", emoji: "🏋️" },
        { quote: "TERRY LOVES HIS FAMILY!", emoji: "👨‍👩‍👧‍👦" },
        { quote: "TERRY LOVES BEING A DAD!", emoji: "👨‍👧‍👦" },
        { quote: "TERRY LOVES HIS WIFE!", emoji: "💍" },
        { quote: "TERRY LOVES HIS JOB!", emoji: "💼" },
        { quote: "TERRY LOVES HIS FRIENDS!", emoji: "🤗" },
        { quote: "TERRY LOVES HIS LIFE!", emoji: "❤️" },
        { quote: "TERRY LOVES EVERYTHING!", emoji: "🎉" },
        { quote: "TERRY LOVES BEING TERRY!", emoji: "💪" },
        { quote: "TERRY LOVES MUSCLE!", emoji: "💪" },
        { quote: "TERRY LOVES STRENGTH!", emoji: "🏋️‍♂️" },
        { quote: "TERRY LOVES POWER!", emoji: "⚡" },
        { quote: "TERRY LOVES ENERGY!", emoji: "🔋" },
        { quote: "TERRY LOVES VITALITY!", emoji: "💪" },
        { quote: "TERRY LOVES HEALTH!", emoji: "🏥" },
        { quote: "TERRY LOVES FITNESS!", emoji: "🏃‍♂️" },
        { quote: "TERRY LOVES NUTRITION!", emoji: "🥗" },
        { quote: "TERRY LOVES WELLNESS!", emoji: "🧘‍♂️" },
        { quote: "TERRY LOVES BALANCE!", emoji: "⚖️" },
        { quote: "TERRY LOVES HARMONY!", emoji: "🎵" }
    ],
    gina: [
        { quote: "I'M BASICALLY A CELEBRITY!", emoji: "✨" },
        { quote: "I'M BASICALLY A GENIUS!", emoji: "🧠" },
        { quote: "I'M BASICALLY A QUEEN!", emoji: "👑" },
        { quote: "I'M BASICALLY A LEGEND!", emoji: "🌟" },
        { quote: "I'M BASICALLY A STAR!", emoji: "⭐" },
        { quote: "I'M BASICALLY A GODDESS!", emoji: "👸" },
        { quote: "I'M BASICALLY A DIVA!", emoji: "💅" },
        { quote: "I'M BASICALLY A BOSS!", emoji: "👔" },
        { quote: "I'M BASICALLY A HERO!", emoji: "🦸‍♀️" },
        { quote: "I'M BASICALLY A WINNER!", emoji: "🏆" },
        { quote: "I'M BASICALLY A CHAMPION!", emoji: "🥇" },
        { quote: "I'M BASICALLY THE BEST!", emoji: "👑" },
        { quote: "I'M BASICALLY A LEADER!", emoji: "🎖️" },
        { quote: "I'M BASICALLY A PIONEER!", emoji: "🚀" },
        { quote: "I'M BASICALLY A TRAILBLAZER!", emoji: "🔥" },
        { quote: "I'M BASICALLY A REVOLUTIONARY!", emoji: "⚡" },
        { quote: "I'M BASICALLY A VISIONARY!", emoji: "🔮" },
        { quote: "I'M BASICALLY A MASTERMIND!", emoji: "🧠" },
        { quote: "I'M BASICALLY A STRATEGIST!", emoji: "🎯" },
        { quote: "I'M BASICALLY A TACTICIAN!", emoji: "⚔️" },
        { quote: "I'M BASICALLY A COMMANDER!", emoji: "🎖️" },
        { quote: "I'M BASICALLY A DIRECTOR!", emoji: "🎬" }
    ],
    boyle: [
        { quote: "I LOVE FOOD!", emoji: "🍕" },
        { quote: "I LOVE COOKING!", emoji: "👨‍🍳" },
        { quote: "I LOVE MY FRIENDS!", emoji: "🤗" },
        { quote: "I LOVE BEING A DETECTIVE!", emoji: "🔍" },
        { quote: "I LOVE MY JOB!", emoji: "💼" },
        { quote: "I LOVE EVERYTHING!", emoji: "❤️" },
        { quote: "I LOVE JAKE!", emoji: "😍" },
        { quote: "I LOVE THE 99TH PRECINCT!", emoji: "🚔" },
        { quote: "I LOVE BEING A COP!", emoji: "👮" },
        { quote: "I LOVE HELPING PEOPLE!", emoji: "🤝" },
        { quote: "I LOVE MY LIFE!", emoji: "🎉" },
        { quote: "I LOVE BEING CHARLES!", emoji: "🥪" },
        { quote: "I LOVE RECIPES!", emoji: "📖" },
        { quote: "I LOVE INGREDIENTS!", emoji: "🥕" },
        { quote: "I LOVE FLAVORS!", emoji: "👅" },
        { quote: "I LOVE AROMAS!", emoji: "👃" },
        { quote: "I LOVE TEXTURES!", emoji: "🤲" },
        { quote: "I LOVE PRESENTATION!", emoji: "🍽️" },
        { quote: "I LOVE GARNISHES!", emoji: "🌿" },
        { quote: "I LOVE SEASONINGS!", emoji: "🧂" },
        { quote: "I LOVE SPICES!", emoji: "🌶️" },
        { quote: "I LOVE HERBS!", emoji: "🌱" },
        { quote: "I LOVE CULINARY ARTS!", emoji: "🎨" }
    ]
}; 